variables: secrets.yml
tasks:

### ANIME-SONARR #
# Get from anime list any shows that have unseen episodes, add to Sonarr and search for missing
# Also added with anime type and tag, tag list from http://localhost:8989/api/tag?apikey=APIKEY

  anime_unseen:
    priority: 1
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    trakt_lookup:
      account: "{? trakt.account ?}"
      username: "{? trakt.account ?}"
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    if:
      - "tvmaze_series_language == 'Japanese' and tvmaze_series_show_type == 'Animation' or 'anime' in trakt_genres": accept
      - trakt_watched: reject
    list_add:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: '{? sonarr.api ?}'
          series_type: anime
          tags: [1]
          root_folder_path: "/{? folder.series ?}"
          ignore_episodes_with_files: yes
          search_missing_episodes: yes

# Get from anime list any shows that have already been seen, add to Sonarr and only get future episodes
# Also added with anime tag, tag list from http://localhost:8989/api/tag?apikey=APIKEY
# Skip ended to keep Sonarr clean

  anime_seen:
    priority: 2
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    trakt_lookup:
      account: "{? trakt.account ?}"
      username: "{? trakt.account ?}"
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    if:
      - "tvmaze_series_language == 'Japanese' and tvmaze_series_show_type == 'Animation' or 'anime' in trakt_genres ": accept
      - "tvdb_status == 'Ended' or trakt_watched == 'False'": reject
    list_add:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: '{? sonarr.api ?}'
          series_type: anime
          tags: [1]
          root_folder_path: "/{? folder.series ?}"
          ignore_episodes_with_files: yes
          ignore_episodes_without_files: yes

### SERIES-SONARR #
# Get from series list any shows that have unseen episodes, add to Sonarr and search for missing

  series_unseen:
    priority: 3
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    trakt_lookup:
      account: "{? trakt.account ?}"
      username: "{? trakt.account ?}"
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    if:
      - trakt_watched: reject
    accept_all: yes
    list_add:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: '{? sonarr.api ?}'
          ignore_episodes_with_files: yes
          root_folder_path: "/{? folder.series ?}"
          search_missing_episodes: yes

# Get from series list any shows that have already been seen, add to Sonarr and only get future episodes
# Skip ended to keep Sonarr clean

  series_seen:
    priority: 4
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    thetvdb_lookup: yes
    trakt_lookup:
      account: "{? trakt.account ?}"
      username: "{? trakt.account ?}"
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    if:
      - "tvdb_status != 'Ended' and trakt_watched": accept
    list_add:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: '{? sonarr.api ?}'
          ignore_episodes_with_files: yes
          ignore_episodes_without_files: yes
          root_folder_path: "/{? folder.series ?}"

### MOVIES-TRAKT #
# Check for new releases matching criteria and add to watchlist

  new-movies:
    priority: 5
    imdb_lookup: yes
    trakt_list:
      username: giladg
      list: latest-releases
      type: movies
      strip_dates: yes
    imdb:
      min_score: 6.5
      min_votes: 5000
      accept_mpaa_ratings:
        - G
        - PG
        - PG-13
    list_add:
      - trakt_list:
          username: '{? trakt.account ?}'
          account: '{? trakt.account ?}'
          list: '{? trakt.movies ?}'
          type: movies

### CLEANUP-SONARR #
# Remove any shows from Sonarr that are not in series list

  sonarr_cleanup:
    delay: 5 days
    priority: 7
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    thetvdb_lookup: yes
    sonarr_list:
      base_url: http://localhost
      port: 8989
      api_key: '{? sonarr.api ?}'
    list_match:
      from:
        - trakt_list:
            account: '{? trakt.account ?}'
            list: '{? trakt.series ?}'
            type: shows
      action: reject
    accept_all: yes
    list_remove:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: '{? sonarr.api ?}'

### CLEAR-SONARR #
# Manual task to clear Sonarr for testing

  clear-sonarr:
    manual: yes
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    accept_all: yes
    list_remove:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: '{? sonarr.api ?}'
          ignore_episodes_with_files: yes
          ignore_episodes_without_files: yes
